sudo: required
language: bash

env:
  global:
  - GOSS_VERSION=0.3.6
  - GOSS_PATH=/usr/local/bin/goss
  - docker_repo=kopano

services:
- docker

stages:
  - build
  - name: release
    if: branch = master

before_install:
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/dgoss -o /usr/local/bin/dgoss
  - sudo chmod +rx /usr/local/bin/goss
  - sudo chmod +rx /usr/local/bin/dgoss
  - sudo apt update && sudo apt install -y expect
  - ./test.exp

install: make build-all

deploy:
  - provider: script
    script: make publish
    on:
      branch: master
